### ISSUE TITLE
rincheat menu not opening on Digimon Story Cyber Sleuth

### ISSUE THREAD

**Issue by boltocrank** [Rinnegatamante/rinCheat#11]
Tested on game in different parts but pressing START+SELECT does nothing, opened other games and it works fine. (Deception IV, Persona 4 Golden)

**Comment by Rinnegatamante** [comment]
Check if amphetamin works. If not, problem is in your dump.

**Comment by boltocrank** [comment]
yep, amphetamin didn't work too, thanks
