### ISSUE TITLE
Some Vitamin 2.0 Games not opening rincheat menu

### ISSUE THREAD

**Issue by boltocrank** [Rinnegatamante/rinCheat#17]
Gravity Rush, Dungeon Travelers and Digimon Story, Amphetamin works but rincheat menu doesn't. All of this games made with Vitamin 2.0.
Got one game made with Vitamin 2.0 that works, Trillion: God of Destruction.

**Comment by gnmmarechal** [comment]
hum. Does Gravity Rush with V2.0 work fine past chapter 1?

**Comment by Rinnegatamante** [comment]
Have you tried both RAM and MMC modes (Hold L trigger on game startup).

**Comment by boltocrank** [comment]
Tested going to MMC mode on trillion, didn,t work, still on RAM mode, did the same with the other games but no change.

**Comment by Rinnegatamante** [comment]
Does the games crashes or just menu doesn't show up?

**Comment by boltocrank** [comment]
I think i found the problem, the line for rincheat in game.txt was gone, don't know how the other games still worked fine and only those 3 didn't work but i put the line back and tested on digimon and it worked.
I will test on the other games and close this if they all work. 

EDIT: Now i got another problem, other games give error C2-12828-1 when trying to run, if i delete the line in game.txt they run ok.
The games that give that error are: Gravity Rush, Freedom Wars and Criminal Girls.
All these games where made with Vitamin 2.0, but i have other Vitamin 2.0 games that work just fine.

**Comment by Rinnegatamante** [comment]
Crash reports without psp2dmp files are useless, also refer to this: https://github.com/Rinnegatamante/rinCheat/issues/10
