### ISSUE TITLE
Can't import decrypted savedata using Major Tom's savedata decryption method

### ISSUE THREAD

**Issue by Cinnamoni** [Rinnegatamante/rinCheat#19]
Using the method from http://pastebin.com/pz9FbTet and importing the savedata yield only one savedata even if there are multiple other savedatas. No icon either.

**Comment by Rinnegatamante** [comment]
Use the export savedata feature in the plugin...

**Comment by Cinnamoni** [comment]
Is there any way to import savedata from retail games to dumped ones then?

**Comment by Rinnegatamante** [comment]
rinCheat can't handle multiple saveslots atm so this is the best you can get actually.
