### ISSUE TITLE
Isn't there any database for Final Fantasy X/X2 please?

### ISSUE THREAD

**Issue by Fadi5555** [Rinnegatamante/rinCheat#22]
@Rinnegatamante please is there any hack for FF XHD/2 please? We really need it at least to be:
Infinity health
Max weapons

And something like that. Please add it.
Also I tried to get my original savedata to my FFx X dump but it never transfer unless I copy Original FFX. Any help please?

**Comment by Rinnegatamante** [comment]
Discuss such questions on forums or reddit.
