### ISSUE TITLE
Please don't stop because of sucks China people

### ISSUE THREAD

**Issue by Fadi5555** [Rinnegatamante/rinCheat#23]
We really like your project so much please don't stop.
That's really so sad.

**Comment by gnmmarechal** [comment]
He's not necessarily stopping, he's closing the source, right?

**Comment by Sans0Serif** [comment]
How to get NTR in 3 easy steps.
1: Get copied.
2: Get mad.
3: Make your project closed source.

**Comment by ErikPshat** [comment]
It's not that he opened or closed the project.
And the thing is that the developer is not fed very well, referring to the entire nation when he used his source one person, for example from China.

And if you would use this source code someone from Italy, Spain, Germany, Russia? Then what, you had to write susks Italy, susks Spain, susks Germany, susks Russia?
