### ISSUE TITLE
On forking

### ISSUE THREAD

**Issue by kaezone** [Rinnegatamante/rinCheat#25]
Does the developer notice include forks? While these are credited by linking to the original repository, it is also classed as a derivative of an ARR repository.

**Comment by Rinnegatamante** [comment]
Theoretically yes but i'm fine with forks since it's kinda impossible to send PRs without a fork.

**Comment by gnmmarechal** [comment]
I guess time to write a license that states everything you can/can't do with the code :P

**Comment by Rinnegatamante** [comment]
I'm not a lawyer and i don't want to bring legal issues here. I just hope common sense of devs will be enough.

**Comment by gnmmarechal** [comment]
You definitely should write something saying specifically which uses are allowed tho. You know that many have no common sense. :/

**Comment by kaezone** [comment]
Common sense didn't stop zCheat.

**Comment by gnmmarechal** [comment]
Nor did it stop YukiFM. You really should write something IMO. Anything like "you can use this for other stuff as long as you credit, etc" or "you may fork this to contribute to this project" or whatever it is you want.

**Comment by Rinnegatamante** [comment]
Maybe reading the readme?
