### ISSUE TITLE
Detect size of value, so we don't need to specify size?

### ISSUE THREAD

**Issue by llakssz** [Rinnegatamante/rinCheat#26]
Instead of doing this:
#999 Max Health

@0xB1A4A231 @0x3E7 @4 (sorry for the tag - I don't know how to remove it)

Would it not be better to do this:
#999 Max Health

@0xB1A4A231 @0x000003E7

Just an idea, thanks.

**Comment by Rinnegatamante** [comment]
It will require a lot more RAM to do so breaking the cheats list support on several games.

**Comment by llakssz** [comment]
Thanks for the input.
