### ISSUE TITLE
cheats dont show up

### ISSUE THREAD

**Issue by Kingpin4087** [Rinnegatamante/rinCheat#29]
im kinda new to this and was wondering what folders you need to put the cheats in for them to show up on the list.

**Comment by mocchimon** [comment]
place your cheatlist in ux0:/data/rinCheat/db named as TITLEID.txt

**Comment by Kingpin4087** [comment]
@thexviet i used the ones provided by the developer and they still dont show up when  in the right folders

**Comment by mocchimon** [comment]
I'm currently using beta 4. Which version are you using? I had trouble with the initial beta and decided to get the latest, so far so good.

**Comment by Kingpin4087** [comment]
im also using beta 4. i just wanted to ask are you also using the .lua cheat files the creator provided or are you using your own

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/rinCheat/issues/30
