### ISSUE TITLE
Dragon Quest Builders Demo Not Save Exporting Correctly

### ISSUE THREAD

**Issue by drummerix** [Rinnegatamante/rinCheat#31]
I downloaded the Dragon Quest Builders Demo and used MaiDumpTool to dump it so I could enable rinCheat on it.  I cannot find anything realtime to cheat with and when I export the saves, one of the files is 0 bytes and when you import them, the save corrupts and causes the game to crash when loading it.

This game has really big save file most likely because of the world made up of blocks like Minecraft.  I think it's this file that is 0 bytes when exporting.

**Comment by drummerix** [comment]
I can confirm it's an issue with the file size being too big.  The last file is 25 MB and that's too much in RAM mode.

I changed savegame.c functions to decrypt like the following:

```
        long size = sceIoLseek(fd, 0, SEEK_END);
        sceIoLseek(fd, 0, SEEK_SET);
        if (0){
            char* data = (char*)malloc(size);
```

I made it always false on the if to do it in chunks.  You can actually do it however you want, but my changes seemed to work, but it takes a very long time to import the saves back when doing it in chunks with Dragon Quest Builders.  Maybe you can improve it.

The import function I changed similar to the following:

```
        long size = sceIoLseek(fd, 0, SEEK_END);

                    if (0){
            char* data = (char*)malloc(size);
```

I tested it and I can now cheat on Dragon Quest Builders using savegames.

**Comment by drummerix** [comment]
I went ahead and modified the savegame.c like attached and it fixes Dragon Quest Builders and doesn't take too long to import also.  I made the buffer 512K and do it in those chunks if ram_mode is detected.  Feel free to use this.

Also when is another release happening?
[savedata.zip](https://github.com/Rinnegatamante/rinCheat/files/505419/savedata.zip)

  I can compile the code but it crashes a lot.

**Comment by Rinnegatamante** [comment]
Title ID of Dragon Quest Builders?

**Comment by drummerix** [comment]
The TitleID for US version is PCSE00934.  Probably same issue if you get the EUR version if you need to though.

**Comment by Rinnegatamante** [comment]
I'm going to add a simple patch, basically if the titleid is detected, mmc mode-like savedata managing is used instead of ram ones.

**Comment by drummerix** [comment]
If you send me the version, I can test it.  The issue was the ram_mode option was trying to allocate 25 MB of memory and failing I assume.  If you look at my code, it seems to fix the issue for me.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/rinCheat/commit/34ce2bad65aa774d39626fa3f01062ceebef7e2c fixes the issue.

**Comment by drummerix** [comment]
I hate to keep complaining, but when I tried that option, it took 20 minutes to import saves into Dragon Quest Builders.  You really need to up the chunk_size to speed up the process if possible.

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/rinCheat/commit/c0c47475a61466c029f193d8ac317e184e8d4d6e
