### ISSUE TITLE
Digimon Story Cyber Sleuth *Coliseum Freezing* 

### ISSUE THREAD

**Issue by mocchimon** [Rinnegatamante/rinCheat#33]
Not sure if anyone else witnessed this issue but has been reoccurring for me pretty constantly.  Link below explains that running Digimon story cyber sleuth EUR(not sure if NA version has the same issue) freezes in the coliseum and periodically while in game.
https://www.reddit.com/r/VitaPiracy/comments/528y62/digimon_story_cyber_sleuth_coloseum_freezing/

**Comment by Rinnegatamante** [comment]
Try to delete net_module.suprx and check if it solves the issue.

**Comment by mocchimon** [comment]
works
