### ISSUE TITLE
STEPS to create cheat

### ISSUE THREAD

**Issue by yushinyuma** [Rinnegatamante/rinCheat#36]
hello can you help step on search cheat?i always use unknown value search on tempar on psp 
But here ,i've tried many time of my search but all of them not work, in metal gear solid 3 and 2013 infected war
1. in metal gear solid i have 36 bullet so how do i start?
   can i search this on any size?or on 1 size only-i have found result on this
2. if i search on 2 or more size., can i puit like this?000000036 or 36000000?
3. when 1st search on Start Absolute Search go back game n change the bullet number go back on cheat menu 2nd search is on Start Absolute Search again or relative search? iam only focusing on Start Absolute Search
4. when i found 1 or 3 codes i save on save offset then edit on vitashell like this (sample) @0x12345678 @0x  (wat do i put here? the 36 value or hex code of 36?)i only put hex code.,
5. when is search 36 i found 20, back on game then 2nd search for 35 found 41 or something.,3 rd search found more.,how to fix that dont get it

**Comment by yushinyuma** [comment]
in my question number 4 wat is the final code @0x12345678 @0x153 @1 or @0x12345678 @0x00000153 @1?.,.,. or can you give me ah steps., to follow  from search to final code thanks

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/rinCheat#how-to-use-value-searcherinjector

https://github.com/Rinnegatamante/rinCheat#how-to-use-cheats-list
