### ISSUE TITLE
Resident evil revelation 2 and FFX request.

### ISSUE THREAD

**Issue by Fadi5555** [Rinnegatamante/rinCheat#38]
Can you please add resident evil revelation 2 and Final fantasy X to could use hack like infinity ammo and strong weapons and something like that.
We really need for this games
Thank you.

**Comment by gnmmarechal** [comment]
rinCheat isn't here for Rinnegatamante to make cheats... He's releasing this for people to make cheats for it. It's not an issue with rinCheat at all.
