### ISSUE TITLE
What is the maximum cheats allowed in a cheatlist?

### ISSUE THREAD

**Issue by mocchimon** [Rinnegatamante/rinCheat#39]
I have a cheatlist with 52 cheats but when I load up rincheat only the first 22 cheats show

**Comment by qyungq** [comment]
Mind sharing the cheat list?

**Comment by mocchimon** [comment]
#99999999 Money
@0x8406F490 @0x05F5E0FF @4
#x99 Usable Item Slot 1
@0x83F51934 @0x63 @1
#x99 Usable Item Slot 2
@0x83F51954 @0x63 @1
#x99 Usable Item Slot 3
@0x83F51974 @0x63 @1
#x99 Usable Item Slot 4
@0x83F51994 @0x63 @1
#x99 Usable Item Slot 5
@0x83F519B4 @0x63 @1
#x99 Usable Item Slot 6
@0x83F519D4 @0x63 @1
#x99 Usable Item Slot 7
@0x83F519F4 @0x63 @1
#x99 Usable Item Slot 8
@0x83F51A14 @0x63 @1
#x99 Usable Item Slot 9
@0x83F51A34 @0x63 @1
#x99 Usable Item Slot 10
@0x83F51A54 @0x63 @1
#x99 Usable Item Slot 11
@0x83F51A74 @0x63 @1
#x99 Usable Item Slot 12
@0x83F51A94 @0x63 @1
#x99 Usable Item Slot 13
@0x83F51AB4 @0x63 @1
#x99 Usable Item Slot 14
@0x83F51AD4 @0x63 @1
#x99 Usable Item Slot 15
@0x83F51AF4 @0x63 @1
#x99 Usable Item Slot 16
@0x83F51B14 @0x63 @1
#x99 Usable Item Slot 17
@0x83F51B34 @0x63 @1
#x99 Usable Item Slot 18
@0x83F51B54 @0x63 @1
#x99 Usable Item Slot 19
@0x83F51B74 @0x63 @1
#x99 useable item slot 20
@0x83F51B94 @0x63 @1
#x99 useable item slot 21
@0x83F51BB4 @0x63 @1
#x99 useable item slot 22
@0x83F51BD4 @0x63 @1
#x99 useable item slot 23
@0x83F51BF4 @0x63 @1
#x99 useable item slot 24
@0x83F51C14 @0x63 @1
#x99 useable item slot 25
@0x83F51C34 @0x63 @1
#x99 useable item slot 26
@0x83F51C54 @0x63 @1
#x99 useable item slot 27
@0x83F51C74 @0x63 @1
#x99 useable item slot 28
@0x83F51C94 @0x63 @1
#x99 useable item slot 29
@0x83F51CB4 @0x63 @1
#x99 useable item slot 30
@0x83F51CD4 @0x63 @1
#x99 useable item slot 31
@0x83F51B94 @0x63 @1
#x99 useable item slot 32
@0x83F51BB4 @0x63 @1
#x99 useable item slot 33
@0x83F51BD4 @0x63 @1
#x99 useable item slot 34
@0x83F51BF4 @0x63 @1
#x99 useable item slot 35
@0x83F51C14 @0x63 @1
#x99 useable item slot 36
@0x83F51C34 @0x63 @1
#x99 useable item slot 37
@0x83F51C54 @0x63 @1
#x99 useable item slot 38
@0x83F51C74 @0x63 @1
#x99 useable item slot 39
@0x83F51C94 @0x63 @1
#x99 useable item slot 40
@0x83F51D14 @0x63 @1
#x99 useable item slot 41
@0x83F51D34 @0x63 @1
#x99 useable item slot 42
@0x83F51D54 @0x63 @1
#x99 useable item slot 43
@0x83F51D74 @0x63 @1
#x99 useable item slot 44
@0x83F51D94 @0x63 @1
#x99 useable item slot 45
@0x83F51DB4 @0x63 @1
#x99 useable item slot 46
@0x83F51DD4 @0x63 @1
#x99 useable item slot 47
@0x83F51DF4 @0x63 @1
#x99 useable item slot 48
@0x83F51E14 @0x63 @1
#x99 useable item slot 49
@0x83F51E34 @0x63 @1
#x99 useable item slot 50
@0x83F51E54 @0x63 @1
#Brave Point A in Slot 1 (Auto Corrects)
@0x83F5192C @0x36 @1

**Comment by yamyi** [comment]
what game are those cheat for??

**Comment by AdyItachi** [comment]
seem like its for digimon cyber sleuth

**Comment by yushinyuma** [comment]
Hello bro can u give sample step in search own cheat?.,my own searched here one of them never work.,may i search wrog steps

**Comment by Rinnegatamante** [comment]
There shouldn't be any kind of limitation. I suggest you to wait for next release which should came soon and check if the issue still happens.

**Comment by qyungq** [comment]
do you also have god eater 2 rage burst offset ?

**Comment by Rinnegatamante** [comment]
@mocchimon Any news about this using the stable version release?

**Comment by mocchimon** [comment]
Tested and still the same issue. I read somewhere about a hidden character maybe that might fix this

**Comment by Rinnegatamante** [comment]
Hidden character? O.o

Anyway, i'm quite sure the problem is caused by low RAM available when reading the cheats database but i could be wrong.

Can you check if changing the order of the cheats modifies something?
