### ISSUE TITLE
Searching values returns nothing in SAO:Lost Song

### ISSUE THREAD

**Issue by yamyi** [Rinnegatamante/rinCheat#40]
when searching for values in sword art online lost song they cant seem to find any value wether it being money state level etc.
always find 0 match

**Comment by Rinnegatamante** [comment]
Not every games have important stuffs on main thread stack or memory block currently scannable in Heap.

**Comment by Rinnegatamante** [comment]
Refer to this https://github.com/Rinnegatamante/rinCheat/issues/20
