### ISSUE TITLE
it crashed when i insert value

### ISSUE THREAD

**Issue by yushinyuma** [Rinnegatamante/rinCheat#41]
Hello again., when i finish to Start Absolute Search  then have found result , what exact steps for next?
the game crash when i inject value
 ca you please answer this on number
1. do i have to inject value at time or 
   go back to game and change na value then back to cheat menu and inject value?
2. do i put hex code or exact number on the game?when start absolutely search

**Comment by Rinnegatamante** [comment]
The decimal number is shown in parenthesis on the right of the hex value.
If you inject a value right after doing a first scan you get for sure multiple offsets and most of them will be illegal offsets.

**Comment by yushinyuma** [comment]
still my work not good.,please check if im doin right
1. go to cheat menu search absolutely value hex 10 money
2. back to game the change the money 9
3. back to cheat menu change 9 hex on search then inject value then search relative search is this okay?

**Comment by Rinnegatamante** [comment]
You should first do a relative search and then inject the new value.

**Comment by yushinyuma** [comment]
but when i i click relative search., no found result

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/rinCheat/issues/20
