### ISSUE TITLE
FFX HD to hack sphere grid moves

### ISSUE THREAD

**Issue by ilya668111** [Rinnegatamante/rinCheat#42]
Hello! Is it possible to hack sphere grid moves in FFX HD? As I understand Rincheat has functionality of Artmoney?

**Comment by ilya668111** [comment]
I tried to do it but no use. Who can write algorithm please?

**Comment by ilya668111** [comment]
Nobody knows?

**Comment by ilya668111** [comment]
so pity

**Comment by Fadi5555** [comment]
We all want a hack for this amazing game. But until now no luck.

**Comment by ilya668111** [comment]
not only me?)
Ok, I'll wait for some news!

**Comment by Rinnegatamante** [comment]
You should ask for such questions in forums or reddit. This is not a rinCheat issue.
