### ISSUE TITLE
full steps

### ISSUE THREAD

**Issue by yushinyuma** [Rinnegatamante/rinCheat#43]
Can you give example step may i,m missing one whynall my code not work.
Can u sample this i have 100 money how to search from 100 to 99 to 98 .to see exact code for that money.. Tnx.

**Comment by Rinnegatamante** [comment]
I've already told you how to so here: https://github.com/Rinnegatamante/rinCheat/issues/41

And it's also explained in the README.

It's useless you open a new issue everytime.

**Comment by yushinyuma** [comment]
But the read on read me nothing help., i am asking how use them by steps., because nothing got work.,ehehe.. Do i search o stack or heap expiremental
