### ISSUE TITLE
Stream: On - Listening on pTrophy

### ISSUE THREAD

**Issue by StallionXD** [Rinnegatamante/rinCheat#44]
Help me please, when I try to stream on my PC I turn the Stream Screen option ON, but it says "Listening to pTrophy" where "pTrophy" mean to be my Vita IP right? so, why I'm having this problem? is there a fix or something? thanks you for your time.
PD: sorry for the bad english.
Edit: in a game it says "Listening on" and just that, it did not show the IP or that pTrophy thing.

**Comment by Rinnegatamante** [comment]
You can try to use the same IP shown in VitaShell when enabling FTP but probably the game you're using won't have enough memory to start the jpeg encoder required for streaming (the pTrophy showing is caused by memory corruption between "official" threads and rinCheat ones).
