### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by jialeyne** [Rinnegatamante/rinCheat#45]
i have 110 money

so i search value 6e-110
Start Absolute Search found 30
change value 6d-109
click insert value
go back on game change the money to 109
go back n cheat menu
click Start Relative Search found 26

i repeat this process many but it only found 26 to 20 only

its wrong i cant get found 1 result
can you correct if wrong

**Comment by Rinnegatamante** [comment]
IT's not wrong. Memory doesn't contain only "plain" values.
