### ISSUE TITLE
Value and Size

### ISSUE THREAD

**Issue by csauceda96** [Rinnegatamante/rinCheat#46]
Trying to figure out how to work this thing still, I managed to save 3 offsets and am trying to test which ones effect my game but I don't know where to get the Value and size from. Example-

Offset- 0x833BCD28

Where do I get the value and size, do I look through my hex editor? Any help is appreciated.

**Comment by Rinnegatamante** [comment]
Hex edit what? You can't hex edit realtime memory.

Everything is explained in the readme.
