### ISSUE TITLE
[Feature Request] RinCheat

### ISSUE THREAD

**Issue by n0k0m3** [Rinnegatamante/rinCheat#47]
1. Search all (populate all values and data, save them temporarily to RAM in RAM mode or as txt in MMC mode)
2. Search changed (search for changed value: changed, increased, decreased, unchanged) - probably 2nd search all + compare with the 1st search all

**Comment by Rinnegatamante** [comment]
Search All = Start Absolute Search
Search changed = Start Relative Search
