### ISSUE TITLE
Noob Questions... Needs the game to be dumped?

### ISSUE THREAD

**Issue by DraconiasF** [Rinnegatamante/rinCheat#48]
long story short: I have Kancolle Kai and want to do some manipulating there. the problem is: I do want to do that on the english patch release, which can you just download as vpk file and install it. I have indeed the cardridged version as well. So do I need to dump the cardridged version from KanColle Kai and would it still works with an applied english patch? Because everything I tried to do doesn't seems to work with this game (If i just press start+select nothing happens within the game) Maybe a video tutorial by installing rincheat would enlighten me and others who are new to that kind of thing...

**Comment by Rinnegatamante** [comment]
I don't get what you're trying to say due to grammatical errors in your english (or it is just me not getting the sense of the phrase, probably this second :P), sorry.
Anyway rinCheat works only with dumps as any other steroid-based plugin.
