### ISSUE TITLE
Use kernel module for heap memory probing

### ISSUE THREAD

**Issue by tippisum** [Rinnegatamante/rinCheat#49]
I have created a kernel plugin capable for a rather complete probing of heap memory. If you are interested in it, here it is: https://github.com/tippisum/vitautils

taiHEN is required for loading kernel plugin.
A small code fragment is attached for demonstrating the usage.
[sample.txt](https://github.com/Rinnegatamante/rinCheat/files/616912/sample.txt)

**Comment by Rinnegatamante** [comment]
I still have to port the whole plugin to taiHEN. Thanks for the tip, i'll surely take a look at it whenever i have enough time to work to this conversion.
