### ISSUE TITLE
PsVita Streaming

### ISSUE THREAD

**Issue by psvita123** [Rinnegatamante/rinCheat#50]
Hello Mr. @Rinnegatamante 
Sir can u please publish a full tutorial for how to stream ps vita to pc????
Any help will be highly appreciated

**Comment by gnmmarechal** [comment]
This isn't a real issue, so this should be asked at the forums imho. At any rate, I might make a tutorial for that myself.

**Comment by Rinnegatamante** [comment]
That's pretty easy and explained in the readme: https://github.com/Rinnegatamante/rinCheat#how-to-use-screen-stream
