### ISSUE TITLE
Screenshot with wrong colors on some games

### ISSUE THREAD

**Issue by Rinnegatamante** [Rinnegatamante/rinCheat#6]
This is caused apparently by a bug in sceDisplayGetFrameBuf. Even if pixelformat is always reported as 0, the encoding used by the game may differ from standard ABGR.

**Comment by coderobe** [comment]
Any (preferably small) games to reproduce this on?

**Comment by Rinnegatamante** [comment]
I noticed this personally with SAO: Lost Song ( http://rinnegatamante.it/site/PCSB00830_94_16721.bmp ) where red channel seems to be considered as alpha at least.

A user also reported that Borderlands 2 has wrong colors but correct alpha this time: https://pbs.twimg.com/media/Cri1FVMXYCAeV7P.jpg:large

**Comment by Rinnegatamante** [comment]
Did another test with The Binding of Isaac: Rebirth and colors are correct.

http://rinnegatamante.it/PCSE00507_97_144825.bmp

**Comment by Rinnegatamante** [comment]
Fixed with https://github.com/Rinnegatamante/rinCheat/commit/9e9c5154b58b820ad06c088592df7f07fd387d74
