### ISSUE TITLE
[Rincheat SE] Some errors

### ISSUE THREAD

**Issue by airainchoc** [Rinnegatamante/rinCheat#61]
Hello, 

I'm having some errors with the latest release of Rincheat SE:
- If my wifi connection is turned on: 
`[String "?"]:1 Syntax error near '/'`
this error does not appear if I turn off the wifi

but then I have:
`[String "?"]:365: attempt to get lenght of a nil value (local 'slot files')`

My vita is 3.60 Fat, running Enso...

Thanks

**Comment by manofsteel2017** [comment]
same issue too :(

**Comment by Rinnegatamante** [comment]
rinCheat SE is going to get an update as soon as SavedataPlus i'm working on will be ready. That issue will be addressed too.

**Comment by manofsteel2017** [comment]
Thanks buddy.

I did donate to you the other day.

Only few dev left. We can't lose you lol
Name. Is Marc A :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Rinnegatamante** [comment]
That bug should be fixed now.

**Comment by pmsobrado** [comment]
I'm getting `[String "?"]:1 Syntax error near '>'.` if connected to wifi, and remote.lua looks like a HTML. Is the update URL/repo/whatever broken?

Thanks.

**Comment by gnmmarechal** [comment]
I took a quick look, the URL seems to be live as far as I can tell.

**Comment by pmsobrado** [comment]
@gnmmarechal That's weird, my remote.lua still creates as a HTML. How does yours look like??
