### ISSUE TITLE
Rincheat SE: Can't get my custom cheat file to work properly

### ISSUE THREAD

**Issue by falcus123** [Rinnegatamante/rinCheat#64]
-- Rainbow Moon (USA)
-- Credits: Slade

needs_crc32 = false

warning = "The Add 999 XP cheat will ensure you go up a level after a fight."

cur_chts = {
	{["name"]="TRISHA SP", ["offsets"]={0x16BF0,0x16BF2}, ["file"]="data0000.bin", ["value"]=0x270F, ["size"]=2},
	{["name"]="GORODO SP", ["offsets"]={0x17588,0x1758A}, ["file"]="data0000.bin", ["value"]=0x270F, ["size"]=2},
	{["name"]="HERO SP", ["offsets"]={0x16724,0x16726}, ["file"]="data0000.bin", ["value"]=0x270F, ["size"]=2},
	{["name"]="DOZERU ARMR SKLMSTR", ["offsets"]={0x17166}, ["file"]="data0000.bin", ["value"]=0x41, ["size"]=1},
	{["name"]="TRISHA WPN SKL", ["offsets"]={0x16C62}, ["file"]="data0000.bin", ["value"]=0x38, ["size"]=1},
	{["name"]="DOZERU MP", ["offsets"]={0x16D50,0x16D58}, ["file"]="data0000.bin", ["value"]=0x190, ["size"]=2},
	{["name"]="HERO WPN Skl", ["offsets"]={0x16796}, ["file"]="data0000.bin", ["value"]=0x38, ["size"]=1},
	{["name"]="Hero armr sklmstr", ["offsets"]={0x167CE}, ["file"]="data0000.bin", ["value"]=0x41, ["size"]=1},
	{["name"]="Trisha Armor SklMstr", ["offsets"]={0x16C9A}, ["file"]="data0000.bin", ["value"]=0x41, ["size"]=1},
	{["name"]="Gorudo Armr SklMstr", ["offsets"]={0x17632}, ["file"]="data0000.bin", ["value"]=0x41, ["size"]=1},
	{["name"]="SERENA SP", ["offsets"]={0x17F20,0x17F22}, ["file"]="data0000.bin", ["value"]=0x270F, ["size"]=2},
	{["name"]="DOZERU WPN SKL", ["offsets"]={0x1712E}, ["file"]="data0000.bin", ["value"]=0x38, ["size"]=1},
	{["name"]="GORODO WPN SKL", ["offsets"]={0x175FA}, ["file"]="data0000.bin", ["value"]=0x38, ["size"]=1},
	{["name"]="Trisha MP", ["offsets"]={0x16884,0x1688C}, ["file"]="data0000.bin", ["value"]=0x190, ["size"]=2}
	{["name"]="Dozeru SP", ["offsets"]={0x170BC,0x170BE}, ["file"]="data0000.bin", ["value"]=0x270F, ["size"]=2},
	{["name"]="PL1 999,999 Pearls", ["offsets"]={0x16714}, ["file"]="data0000.bin", ["value"]=0xF423F, ["size"]=4},
	{["name"]="PL1 Add 1k XP", ["offsets"]={0x19688}, ["file"]="data0000.bin", ["value"]=0x3E8, ["size"]=2},
	{["name"]="HERO WPN Skl", ["offsets"]={0x16796}, ["file"]="data0000.bin", ["value"]=0x38, ["size"]=1},
	{["name"]="PL1 MP", ["offsets"]={0x163B8,0x163C0}, ["file"]="data0000.bin", ["value"]=0x190, ["size"]=2},
	{["name"]="250 Recovery Items Slots", ["offsets"]={0x15954}, ["file"]="data0000.bin", ["value"]=0xFA, ["size"]=1},
	{["name"]="250 Misc. Items Slots", ["offsets"]={0x15958}, ["file"]="data0000.bin", ["value"]=0xFA, ["size"]=1},
	{["name"]="250 Weapons Items Slots", ["offsets"]={0x1595C}, ["file"]="data0000.bin", ["value"]=0xFA, ["size"]=1},
	{["name"]="250 Armor Items Slots", ["offsets"]={0x15960}, ["file"]="data0000.bin", ["value"]=0xFA, ["size"]=1},
	{["name"]="250 Materials Slots", ["offsets"]={0x15964}, ["file"]="data0000.bin", ["value"]=0xFA, ["size"]=1},
	{["name"]="Shop Level", ["offsets"]={0x10B}, ["file"]="data0000.bin", ["value"]=0x02, ["size"]=1},
	{["name"]="Trisha Add 1k XP", ["offsets"]={0x196A0}, ["file"]="data0000.bin", ["value"]=0x3E8, ["size"]=2},
	{["name"]="Trisha Pearls", ["offsets"]={0x16BE0}, ["file"]="data0000.bin", ["value"]=0xF423F, ["size"]=4},
	{["name"]="Trisha MP", ["offsets"]={0x16884,0x168AC}, ["file"]="data0000.bin", ["value"]=0x190, ["size"]=2},
	{["name"]="999,999,999 Coins", ["offsets"]={0x104}, ["file"]="data0000.bin", ["value"]=0x3B9AC9FF, ["size"]=4},
	{["name"]="GORODO SP", ["offsets"]={0x17588,0x1758A}, ["file"]="data0000.bin", ["value"]=0x270F, ["size"]=2},
	{["name"]="SERENA HP", ["offsets"]={0x17BB0,0x17BB8}, ["file"]="data0000.bin", ["value"]=0x190, ["size"]=2},
	{["name"]="SERENA MP", ["offsets"]={0x17BB4,0x17BBC}, ["file"]="data0000.bin", ["value"]=0x190, ["size"]=2},
	{["name"]="TRISHA WPN SKL", ["offsets"]={0x16C62}, ["file"]="data0000.bin", ["value"]=0x38, ["size"]=1},
	{["name"]="DOZERU MP", ["offsets"]={0x16D50,0x16D58}, ["file"]="data0000.bin", ["value"]=0x190, ["size"]=2},
	{["name"]="HERO WPN Skl", ["offsets"]={0x16796}, ["file"]="data0000.bin", ["value"]=0x38, ["size"]=1},
	{["name"]="250 Weapons Items Slots", ["offsets"]={0x1595C}, ["file"]="data0000.bin", ["value"]=0xFA, ["size"]=1},
	{["name"]="250 Armor Items Slots", ["offsets"]={0x15960}, ["file"]="data0000.bin", ["value"]=0xFA, ["size"]=1},
	{["name"]="250 Materials Slots", ["offsets"]={0x15964}, ["file"]="data0000.bin", ["value"]=0xFA, ["size"]=1},
	{["name"]="SERENA SP", ["offsets"]={0x17F20,0x17F22}, ["file"]="data0000.bin", ["value"]=0x270F, ["size"]=2}
}

this is the contents of my .lua file....but i get  the error [string ''?''] :23: '}' expected (to close '{'  at line 8) near '{'

this only happen when i try to add offsets i found to the existing .lua file for this game:changing the existing codes' offsets,values.etc allows the codes to work fine....but adding more causes this error...please help! heres my actual file...remove the .txt part of the file
[PCSE00273.lua.txt](https://github.com/Rinnegatamante/rinCheat/files/1570041/PCSE00273.lua.txt)

btw,some of these are the default codes

**Comment by Rinnegatamante** [comment]
As the error says, your file has a syntax error related to not properly using {} brackets.

**Comment by falcus123** [comment]
so how would i properly arrange the above codes?i cannot tell where the mistyped bracket is...

**Comment by Rinnegatamante** [comment]
Line 22 is missing a ,

**Comment by falcus123** [comment]
corrected,i will try this new file out in a moment
edit:works now,thanks Rinnegatamante!
